-- Ortak Plan — PostgreSQL schema (Supabase / PGlite).
--
-- Idempotent: safe to run on every deploy (`npm run db:migrate`) and applied
-- automatically on the first request of a cold start when tables are missing.
--
-- Dates and times are stored as ISO-8601 TEXT with the binary "C" collation so
-- that string comparison == chronological order regardless of the database's
-- default collation (Supabase uses en_US.UTF-8, which ignores punctuation):
--   * calendar dates      'YYYY-MM-DD'
--   * instants (UTC)      'YYYY-MM-DDTHH:MM:SS.sssZ'
-- Events keep two formats on purpose: all-day events store calendar dates, timed
-- events store UTC instants (see server/src/services/events.js).

CREATE TABLE IF NOT EXISTS households (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  invite_code TEXT NOT NULL UNIQUE,
  created_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  initial TEXT NOT NULL,
  color TEXT NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_household ON users (household_id);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  start TEXT COLLATE "C" NOT NULL,
  "end" TEXT COLLATE "C" NOT NULL,
  all_day BOOLEAN NOT NULL DEFAULT FALSE,
  location TEXT NOT NULL DEFAULT '',
  color TEXT,
  visibility TEXT NOT NULL DEFAULT 'shared' CHECK (visibility IN ('shared', 'private')),
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_household_start ON events (household_id, start);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'doing', 'done')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  due_date TEXT COLLATE "C",
  position DOUBLE PRECISION NOT NULL DEFAULT 0,
  visibility TEXT NOT NULL DEFAULT 'shared' CHECK (visibility IN ('shared', 'private')),
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  completed_at TEXT COLLATE "C"
);
CREATE INDEX IF NOT EXISTS idx_tasks_household ON tasks (household_id, status, position);

CREATE TABLE IF NOT EXISTS goals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  period TEXT NOT NULL CHECK (period IN ('daily', 'weekly', 'monthly')),
  period_start TEXT COLLATE "C" NOT NULL,
  period_end TEXT COLLATE "C" NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  done BOOLEAN NOT NULL DEFAULT FALSE,
  visibility TEXT NOT NULL DEFAULT 'shared' CHECK (visibility IN ('shared', 'private')),
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_goals_household ON goals (household_id, period, period_start);

CREATE TABLE IF NOT EXISTS pages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_id INTEGER NOT NULL REFERENCES households(id) ON DELETE CASCADE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES pages(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  content JSONB NOT NULL DEFAULT '[]'::jsonb,
  period TEXT CHECK (period IS NULL OR period IN ('daily', 'weekly', 'monthly')),
  period_start TEXT COLLATE "C",
  period_end TEXT COLLATE "C",
  visibility TEXT NOT NULL DEFAULT 'shared' CHECK (visibility IN ('shared', 'private')),
  position DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pages_household ON pages (household_id, parent_id, position);
CREATE INDEX IF NOT EXISTS idx_pages_period ON pages (household_id, period, period_start);
CREATE INDEX IF NOT EXISTS idx_pages_parent ON pages (parent_id);

-- Supabase exposes the public schema through its Data API (PostgREST) to anyone
-- holding the project's anon key. The app only talks to the database through the
-- Express API (as the table owner, which bypasses RLS), so enable RLS with no
-- policies: this blocks all Data API access while leaving the API unaffected.
ALTER TABLE households ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE pages ENABLE ROW LEVEL SECURITY;
